server:
  # 前端模板调用的端口为8989，故保持一致
  port: 8989

spring:
  profiles:
    # 获取framework模块中的application-common.yml配置
    active: common

  datasource:
    url: jdbc:mysql://192.168.18.111:3306/hunter_blog
    username: root
    password: 123456.root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.18.111
      port: 6379
      database: 0

  servlet:
    multipart:
      # 上传的单个文件大小限制
      max-file-size: 20MB
      # 整个请求的大小限制，可以包含多个文件
      max-request-size: 20MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除，工作方式：
      #   插入：逻辑删除字段的值不受限制。
      #   查找：自动添加条件，过滤掉标记为已删除的记录。
      #   更新：防止更新已删除的记录。
      #   删除：将删除操作转换为更新操作，标记记录为已删除。
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键自增
      id-type: auto